defaults: &defaults
  docker:
    - image: circleci/node:9
  working_directory: ~/prisma

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create package-lock.json checksum
          command: sha256sum package-lock.json > .package-lock-sum
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".package-lock-sum" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".package-lock-sum" }}
      - save_cache:
          paths:
            - ~/prisma
          key: v1-repo-{{ .Revision }}
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
          - v1-build-{{ .Revision }}
      - run:
          name: Release
          command: npx semantic-release || true

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
